#ifndef JSONMODULES_GLOBAL_H
#define JSONMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(JSONMODULES_LIBRARY)
#  define JSONMODULESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define JSONMODULESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JSONMODULES_GLOBAL_H
