#ifndef FASTCPPCSVPARSER_GLOBAL_H
#define FASTCPPCSVPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FASTCPPCSVPARSER_LIBRARY)
#  define FASTCPPCSVPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FASTCPPCSVPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FASTCPPCSVPARSER_GLOBAL_H
